// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfhD5bwy0NIiefJBsQLGB8_6GIW3lVYgk',
    appId: '1:765527137424:web:b5f44e5c0ecec74dcb4c15',
    messagingSenderId: '765527137424',
    projectId: 'flutter-login-590eb',
    authDomain: 'flutter-login-590eb.firebaseapp.com',
    storageBucket: 'flutter-login-590eb.firebasestorage.app',
    measurementId: 'G-3XB13XC8C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdqUPDifhGx84weHqw_WyHMlaVvq6OHKE',
    appId: '1:765527137424:android:8a81df8a3615fea7cb4c15',
    messagingSenderId: '765527137424',
    projectId: 'flutter-login-590eb',
    storageBucket: 'flutter-login-590eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVVvDzcjKZL-J3aP1NQ6Ztv0BiaRmUrus',
    appId: '1:765527137424:ios:6d238f45ff6afd5dcb4c15',
    messagingSenderId: '765527137424',
    projectId: 'flutter-login-590eb',
    storageBucket: 'flutter-login-590eb.firebasestorage.app',
    iosClientId: '765527137424-ferbskav8sdhrrkrm4u30atmfnu3p8hv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseWithLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVVvDzcjKZL-J3aP1NQ6Ztv0BiaRmUrus',
    appId: '1:765527137424:ios:6d238f45ff6afd5dcb4c15',
    messagingSenderId: '765527137424',
    projectId: 'flutter-login-590eb',
    storageBucket: 'flutter-login-590eb.firebasestorage.app',
    iosClientId: '765527137424-ferbskav8sdhrrkrm4u30atmfnu3p8hv.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseWithLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfhD5bwy0NIiefJBsQLGB8_6GIW3lVYgk',
    appId: '1:765527137424:web:bd5f75251e8cae1bcb4c15',
    messagingSenderId: '765527137424',
    projectId: 'flutter-login-590eb',
    authDomain: 'flutter-login-590eb.firebaseapp.com',
    storageBucket: 'flutter-login-590eb.firebasestorage.app',
    measurementId: 'G-4172PHWJ71',
  );
}
